# Generated by Django 3.0 on 2019-12-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.PositiveIntegerField(blank=True)),
                ('town', models.CharField(blank=True, max_length=256)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('building', models.CharField(blank=True, max_length=256)),
                ('apartment', models.PositiveIntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')])),
                ('import_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='promotion.Import')),
                ('relatives', models.ManyToManyField(blank=True, related_name='_citizen_relatives_+', to='promotion.Citizen')),
            ],
        ),
    ]
